baseURL = "https://l-f-souza.github.io/AddSemanticaWebsite/"
languageCode = "en-us"
title = "SEMANTICA"

[params]
  description = "SEMANTICA: Your intelligence Hub"
  descriptionfooter = "SEMANTICA: a product by Mosaic.pt"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 4
  [[menu.main]]
    name = ""
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = ""
    url = "/features/"
    weight = 3
  [[menu.main]]
    name = ""
    url = "/docs/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
